import type {
  Asset,
  Estate,
  Incident,
  NormalizedQuote,
  Organization,
  Vendor,
  WorkOrder,
} from '../../types/domain';

export const initialOrganization: Organization = {
  id: 'ORG-ASTERA-01',
  name: 'Nusantara Heritage Holdings Family Office',
  policySetId: 'POL-STANDARD-2026',
  createdAt: '2026-01-01T00:00:00.000Z',
};

export const initialEstates: Estate[] = [
  {
    id: 'EST-BLI-01',
    organizationId: 'ORG-ASTERA-01',
    label: 'Bali Villa',
    code: 'BLI',
    location: 'Uluwatu, Bali',
    timezone: 'Asia/Makassar',
    status: 'ACTIVE',
    activeIncidentsCount: 1,
    totalAssetsCount: 2,
    monthlyBudgetMinorUnits: 150000000,
    currency: 'IDR',
    createdAt: '2026-01-10T00:00:00.000Z',
  },
  {
    id: 'EST-JKT-01',
    organizationId: 'ORG-ASTERA-01',
    label: 'Jakarta Residence',
    code: 'JKT',
    location: 'Menteng, Jakarta Pusat',
    timezone: 'Asia/Jakarta',
    status: 'ACTIVE',
    activeIncidentsCount: 0,
    totalAssetsCount: 2,
    monthlyBudgetMinorUnits: 250000000,
    currency: 'IDR',
    createdAt: '2026-01-10T00:00:00.000Z',
  },
];

export const initialAssets: Asset[] = [
  {
    id: 'BLI-HVAC-04',
    estateId: 'EST-BLI-01',
    estateLabel: 'Bali Villa',
    spaceId: 'SPC-BLI-MP',
    spaceLabel: 'Master Pavilion',
    name: 'Master-suite HVAC',
    category: 'HVAC',
    state: 'Attention',
    nextScheduledService: 'Follow-up · 13 Sep',
    location: 'North Wing · Master Pavilion',
    serialNumber: 'SN-VRV-9482-ID',
    specifications: 'Daikin VRV Multi-Split 14 kW · R32 Eco-refrigerant',
    lastServiceDate: '14 Jun 2026 (Quarterly coil flush)',
    telemetry: [
      { label: 'Condensate Tray', value: 'High Level Alert', status: 'warning', timestamp: '2026-08-29T08:30:00.000Z' },
      { label: 'Compressor Temp', value: '38.4°C', status: 'good', timestamp: '2026-08-29T08:30:00.000Z' },
      { label: 'Air Flow Rate', value: '920 CFM', status: 'normal', timestamp: '2026-08-29T08:30:00.000Z' },
    ],
    logs: [
      { date: '29 Aug 2026', summary: 'Emergency condensate line isolation by Estate Manager', technician: 'Staff Lead' },
      { date: '14 Jun 2026', summary: 'Routine pre-dry season chemical flush & filter change', technician: 'Bali Climate Works' },
    ],
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: '2026-08-29T08:30:00.000Z',
  },
  {
    id: 'JKT-PWR-02',
    estateId: 'EST-JKT-01',
    estateLabel: 'Jakarta Residence',
    spaceId: 'SPC-JKT-UT',
    spaceLabel: 'Utility Vault',
    name: '80 kVA backup generator',
    category: 'Power',
    state: 'Scheduled',
    nextScheduledService: 'Fuel inspection · 3 Sep',
    location: 'Sub-level B1 · Utility Vault',
    serialNumber: 'SN-GEN-5510-JK',
    specifications: 'Perkins 1104D Turbo Diesel · Sound-attenuated enclosure',
    lastServiceDate: '12 Aug 2026 (Monthly automated load run)',
    telemetry: [
      { label: 'Fuel Reservoir', value: '88% (420 L)', status: 'good', timestamp: '2026-08-29T08:30:00.000Z' },
      { label: 'Battery Health', value: '26.8 V (Optimal)', status: 'good', timestamp: '2026-08-29T08:30:00.000Z' },
      { label: 'Transfer Switch', value: 'Standby / Auto', status: 'normal', timestamp: '2026-08-29T08:30:00.000Z' },
    ],
    logs: [
      { date: '12 Aug 2026', summary: '30-minute full transfer simulation passed without voltage sag', technician: 'Capital Power Care' },
      { date: '04 May 2026', summary: 'Engine oil filter & fuel separator replacement', technician: 'Capital Power Care' },
    ],
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: '2026-08-29T08:30:00.000Z',
  },
  {
    id: 'BLI-POOL-03',
    estateId: 'EST-BLI-01',
    estateLabel: 'Bali Villa',
    spaceId: 'SPC-BLI-PH',
    spaceLabel: 'Pump House',
    name: 'Infinity-pool circulation pump',
    category: 'Water',
    state: 'Scheduled',
    nextScheduledService: 'Seal replacement · 2 Sep',
    location: 'Lower Cliffside Pump House',
    serialNumber: 'SN-PMP-2294-BL',
    specifications: 'Hayward TriStar 3.0 HP Variable Speed Pump',
    lastServiceDate: '01 Jul 2026 (Impeller inspection)',
    telemetry: [
      { label: 'Flow Velocity', value: '145 GPM', status: 'normal', timestamp: '2026-08-29T08:30:00.000Z' },
      { label: 'Motor Vibration', value: '2.4 mm/s (Elevated)', status: 'warning', timestamp: '2026-08-29T08:30:00.000Z' },
      { label: 'Line Pressure', value: '18.2 PSI', status: 'good', timestamp: '2026-08-29T08:30:00.000Z' },
    ],
    logs: [
      { date: '01 Jul 2026', summary: 'Re-greased mechanical drive bearing', technician: 'Island Estate Eng.' },
    ],
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: '2026-08-29T08:30:00.000Z',
  },
  {
    id: 'JKT-SEC-03',
    estateId: 'EST-JKT-01',
    estateLabel: 'Jakarta Residence',
    spaceId: 'SPC-JKT-GH',
    spaceLabel: 'Gatehouse Main',
    name: 'Perimeter security system',
    category: 'Security',
    state: 'Healthy',
    nextScheduledService: 'Firmware review · 18 Sep',
    location: 'Gatehouse Main & Perimeter Fence',
    serialNumber: 'SN-SEC-8821-JK',
    specifications: 'FLIR Thermal LiDAR + AI Perimeter Intrusion Hub',
    lastServiceDate: '20 Aug 2026 (Optical alignment & IR calibration)',
    telemetry: [
      { label: 'Sensors Online', value: '24 / 24 Active', status: 'good', timestamp: '2026-08-29T08:30:00.000Z' },
      { label: 'Network Latency', value: '4 ms (Fiber Ring)', status: 'good', timestamp: '2026-08-29T08:30:00.000Z' },
      { label: 'Tamper Alarm', value: 'Armed & Normal', status: 'normal', timestamp: '2026-08-29T08:30:00.000Z' },
    ],
    logs: [
      { date: '20 Aug 2026', summary: 'IR illuminator cleaning and perimeter optical recalibration', technician: 'Internal Security Team' },
    ],
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: '2026-08-29T08:30:00.000Z',
  },
];

export const initialVendors: Vendor[] = [
  {
    id: 'VND-BLI-01',
    organizationId: 'ORG-ASTERA-01',
    name: 'Bali Climate Works',
    category: 'HVAC & moisture control',
    primaryContact: 'I Wayan S. (Certified Master Technician)',
    phone: '+62 361 8849 011',
    email: 'dispatch@baliclimateworks.id',
    serviceRegions: ['Bali Villa', 'Uluwatu', 'Seminyak'],
    averageSlaMinutes: 120, // 2h
    compliance: {
      licenseNumber: 'BUJK #882-BLI',
      insuranceValidUntil: '2027-12-31T00:00:00.000Z',
      backgroundCheckPassed: true,
      ndaSigned: true,
      verifiedStatus: 'VERIFIED',
    },
    rating: 4.9,
    completedJobsCount: 38,
    activeStatus: 'ACTIVE',
  },
  {
    id: 'VND-BLI-02',
    organizationId: 'ORG-ASTERA-01',
    name: 'Island Estate Engineering',
    category: 'General maintenance',
    primaryContact: 'Ketut A. (Senior MEP Engineer)',
    phone: '+62 361 7721 902',
    email: 'service@islandestate-eng.com',
    serviceRegions: ['Bali Villa', 'Denpasar', 'Ubud'],
    averageSlaMinutes: 240, // 4h
    compliance: {
      licenseNumber: 'SIUP #419-DEN',
      insuranceValidUntil: '2027-06-30T00:00:00.000Z',
      backgroundCheckPassed: true,
      ndaSigned: true,
      verifiedStatus: 'VERIFIED',
    },
    rating: 4.7,
    completedJobsCount: 24,
    activeStatus: 'ACTIVE',
  },
  {
    id: 'VND-JKT-01',
    organizationId: 'ORG-ASTERA-01',
    name: 'Capital Power Care',
    category: 'Power & generators',
    primaryContact: 'Bambang R. (High-Voltage Certified Specialist)',
    phone: '+62 21 5509 2311',
    email: 'emergency@capitalpower.co.id',
    serviceRegions: ['Jakarta Residence', 'Menteng', 'Kebayoran'],
    averageSlaMinutes: 180, // 3h
    compliance: {
      licenseNumber: 'Kementerian ESDM #102-JKT',
      insuranceValidUntil: '2026-12-31T00:00:00.000Z',
      backgroundCheckPassed: true,
      ndaSigned: true,
      verifiedStatus: 'VERIFIED',
    },
    rating: 4.8,
    completedJobsCount: 31,
    activeStatus: 'ACTIVE',
  },
];

export const initialIncidents: Incident[] = [
  {
    id: 'INC-2026-089',
    referenceNumber: 'INC-2026-089',
    estateId: 'EST-BLI-01',
    estateLabel: 'Bali Villa',
    assetId: 'BLI-HVAC-04',
    assetName: 'Master-suite HVAC',
    severity: 'HIGH',
    status: 'AWAITING_APPROVAL',
    summary: 'Master Suite HVAC condensate drain line backflow',
    description:
      'Secondary condensate pan sensor triggered alarm at 08:30 WITA. Moisture detector registered 84% RH in ceiling cavity. Temporary containment active.',
    reportedBy: 'Staff Lead',
    reportedByRole: 'estate_manager',
    reportedAt: '2026-08-29T08:32:00.000Z',
    updatedAt: '2026-08-29T09:48:00.000Z',
    evidence: [
      {
        id: 'EVD-089-01',
        incidentId: 'INC-2026-089',
        storageKey: 'evidence/inc-089/condensate-tray.jpg',
        mediaType: 'photo',
        fileName: 'condensate-tray-photo.jpg',
        fileSizeBytes: 1420500,
        checksumSha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        url: '/evidence/condensate-tray.jpg',
        capturedAt: '2026-08-29T08:35:00.000Z',
        note: 'Moisture accumulation on secondary overflow tray',
      },
    ],
    triage: {
      suggestedSeverity: 'HIGH',
      confidenceScore: 0.94,
      reasoning:
        'Active moisture containment risk detected. Potential ceiling teak finish damage and guest pavilion disruption if not resolved prior to guest arrival.',
      citations: [
        'Condensate Tray sensor reading: High Level Alert',
        'Ceiling humidity: 84% RH',
      ],
      recommendedSpecialty: 'Commercial HVAC & Moisture Remediation',
      containmentSteps: [
        {
          stepNumber: 1,
          action: 'Isolate primary drain valve and switch HVAC unit to fan-only mode.',
          targetRole: 'estate_manager',
          completed: true,
          completedAt: '2026-08-29T08:45:00.000Z',
        },
        {
          stepNumber: 2,
          action: 'Place catchment basin and secondary moisture sensor under ceiling cavity.',
          targetRole: 'steward',
          completed: true,
          completedAt: '2026-08-29T08:52:00.000Z',
        },
        {
          stepNumber: 3,
          action: 'Review normalized vendor quotes and authorize certified technician dispatch.',
          targetRole: 'principal',
          completed: false,
        },
      ],
      aiModelVersion: 'astera-triage-advisory-v2.6',
      triagedAt: '2026-08-29T08:34:00.000Z',
      humanOverrideApplied: false,
    },
    selectedQuoteId: 'QUO-BLI-01',
  },
];

export const initialQuotes: NormalizedQuote[] = [
  {
    id: 'QUO-BLI-01',
    incidentId: 'INC-2026-089',
    vendorId: 'VND-BLI-01',
    vendorName: 'Bali Climate Works',
    vendorRating: 4.9,
    totalAmountMinorUnits: 18500000, // Rp 18,500,000
    currency: 'IDR',
    breakdown: {
      laborMinorUnits: 7500000,
      partsMinorUnits: 9200000,
      permitMinorUnits: 0,
      taxMinorUnits: 1800000,
    },
    etaHours: 2,
    estimatedArrivalTimestamp: '2026-08-29T11:48:00.000Z',
    warrantyMonths: 12,
    scopeDescription:
      'Emergency vacuum line clear, ultrasonic sensor replacement, and antimicrobial ceiling sanitization.',
    riskRating: 'LOW',
    aiRecommendationScore: 94,
    aiRecommendationRationale:
      'Recommended: 2h rapid arrival SLA before evening guest check-in, 12-month full parts/labor warranty, top 4.9 vendor score with 38 verified jobs.',
    isAiRecommended: true,
    complianceVerified: true,
    submittedAt: '2026-08-29T09:15:00.000Z',
  },
  {
    id: 'QUO-BLI-02',
    incidentId: 'INC-2026-089',
    vendorId: 'VND-BLI-02',
    vendorName: 'Island Estate Engineering',
    vendorRating: 4.7,
    totalAmountMinorUnits: 14200000, // Rp 14,200,000
    currency: 'IDR',
    breakdown: {
      laborMinorUnits: 6000000,
      partsMinorUnits: 6800000,
      permitMinorUnits: 0,
      taxMinorUnits: 1400000,
    },
    etaHours: 4,
    estimatedArrivalTimestamp: '2026-08-29T13:48:00.000Z',
    warrantyMonths: 6,
    scopeDescription: 'Standard line blowout, replacement float switch, basic coil check.',
    riskRating: 'MEDIUM',
    aiRecommendationScore: 78,
    aiRecommendationRationale:
      'Lower upfront cost (Rp 14.2M vs 18.5M), but longer 4h ETA window and shorter 6-month warranty.',
    isAiRecommended: false,
    complianceVerified: true,
    submittedAt: '2026-08-29T09:25:00.000Z',
  },
];

export const initialWorkOrders: WorkOrder[] = [];
